services:
  postgres:
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER=dbdb
      - MINIO_ROOT_PASSWORD=dbdbdbdb
    command: server ~/minio --console-address :9090
    ports:
      - 9090:9090
      - 9000:9000
    volumes:
      - minio-data:/minio

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local

networks:
  app-network:
    driver: bridge