spring:
  application:
    name: hack-template
  datasource:
    url: jdbc:postgres://localhost:5432/db
    username: db
    password: db
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretKey: alskdjsdfhlaksdjffhladkfsfhldaksadfhladasdfhljlfhaklfkjadsfhjadkslffhdajlskffhjldkasdfhjkladasdfhjlkasdfjlasdfjkdhsajflfhdsljkffhdasljkfhdasdjklflfhladjsffhaljdssdfhjlkadsasdfhjklsdaasdfhlasdfhladasdflhfhs
  expirationTime: 3600000 # 1 hour in milliseconds

springdoc:
  swagger-ui:
    path: /api-docs

minio:
  bucket: images
  access-key: bimbimbambam
  secret-key: bimbimbambam
  url: http://localhost:9000

